version: '3'

# networks
networks:
  reverse-proxy:
    external:
      name: reverse-proxy
  # internal network
  internal:
    driver: bridge

# services
services:

  # Nginx
  sveltebrasil-nginx:
    image: webdevops/nginx
    container_name: sveltebrasil-nginx
    restart: always
    networks:
      - internal
      - reverse-proxy
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
      - .docker/sveltebrasil-nginx/opt/docker/etc/nginx/vhost.common.d/cache.conf:/opt/docker/etc/nginx/vhost.common.d/cache.conf
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/app/public
      - WEB_DOCUMENT_INDEX=index.html
      - VIRTUAL_HOST=sveltebrasil.dev
      - LETSENCRYPT_HOST=sveltebrasil.dev
      - LETSENCRYPT_EMAIL=wilcorrea@gmail.com
